name = "puzzle-game-api"
main = "src/index.js"
compatibility_date = "2023-12-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "puzzle-game-db"
database_id = "3d0041cc-7075-42bd-b34b-f96c54e0d1b7"

# R2 Bucket
[[r2_buckets]]
binding = "PUZZLE_BUCKET"
bucket_name = "puzzle-assets"

# Environment Variables
[vars]
ENVIRONMENT = "development"

# Build configuration
[build]
command = "npm run build"

# Site binding for serving SPA
[site]
bucket = "./spa/dist"

# Routes for custom domain (optional)
# routes = [
#   { pattern = "puzzle-api.example.com/*", zone_name = "example.com" }
# ]